### ISSUE TITLE
Define the basic structure of the repository

### ISSUE THREAD

**Issue by dmalatesta** [open-source-adventures/adventures#1]

**Comment by dmalatesta** [comment]
I added you as well @Your1Nightmare since it's an important decision :)
So we have a couple of ideas at the moment:

Idea 1:
```
    /(root)
    |
    +-- open-legend/
    |   |
    |   +-- ...
    +-- 5e/
        |
        +-- Really Cool Adventure/
        |   |
        |   +-- chapter1.md
        |   +-- chapter2.md
        |   +-- ...
        |
        +-- Another Adventure/
            |
            +-- adventure.md
            +-- images/
                |
                +-- npc.png
```

Idea 2:
```
    /(root)
    |
    |-- open-legend/
    |   |
    |   +-- author-name
    |       |
    |       + ... (adventures in sub directories like idea 1)
    |
    +-- 5e
        |
        +-- ...
```

Idea 3:
```
    /(root)
    |
    |-- author-name/
    |   |
    |   +-- open-legend/
    |   |   |
    |   |   + ... (adventures in sub directories like idea 1)
    |   |
    |   +-- 5e/
    |
    +-- another-author/
        |
        +-- ...
```

What do you think?

**Comment by Your1Nightmare** [comment]
I think I prefer Idea 2. While I would love to highlight the original author, that could lead to more wide structure than a deeper one. Idea 2 is a good middle ground for that.

**Comment by dmalatesta** [comment]
Ok, I think we can go for it then

**Comment by dmalatesta** [comment]
I created the wiki page for this.

https://github.com/open-source-adventures/adventures/wiki/Repository-Structure

We can close the issue. If we want to change the structure we can create a new issue or just update the wiki page.
